### ISSUE TITLE
Update command breaks profiles with `pass` instead of `password`

### ISSUE THREAD

**Issue by ghost** [zowe/zowe-cli-scs-plugin#21]
Some profiles used to have a field named `pass` instead of `password`. If these profiles store credentials in plain text, when the `scs update` command runs, it handles `user` correctly but breaks the password field.

Original:
```
user: my_user
pass: my_pass
```

After `scs update`:
```
user: "managed by @zowe/secure-credential-store-for-zowe-cli"
password: my_pass
pass: null
```

**Comment by t1m0thyj** [comment]
Closing since this plug-in is obsolete; Zowe CLI now has built-in support for storing secrets
