### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli-scs-plugin#6]
As a developer, I'd like to see a higher quality standard. (maybe target 80%)

![image](https://user-images.githubusercontent.com/37381190/75778076-21c5b680-5d25-11ea-9c5b-4e250375e80e.png)

**Comment by t1m0thyj** [comment]
Closing since this plug-in is obsolete; Zowe CLI now has built-in support for storing secrets
